name: Linux GUI

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/build-gui_linux.yml'
      - 'gui/src/**'

  pull_request:
    branches:
      - master
    paths:
      - '.github/workflows/build-gui_linux.yml'
      - 'gui/src/**'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion: '==2.1.*'
          version: '6.4.1'
          target: 'desktop'
          modules: 'qtserialport'
          install-deps: 'true'

      - name: Build
        working-directory: ${{github.workspace}}        
        run: |
          cd gui/src
          qmake HeadTracker.pro
          make -j`nproc`
          make INSTALL_ROOT=../../../appdir install
          cd ../../

      - name: LinDeployQT
        working-directory: ${{github.workspace}}
        run: |
          mkdir ../appdir/usr/share
          mkdir ../appdir/usr/share/applications          
          mkdir ../appdir/usr/share/icons
          mkdir ../appdir/usr/share/icons/hicolor
          mkdir ../appdir/usr/share/icons/hicolor/256x256
          mkdir ../appdir/usr/share/icons/hicolor/256x256/apps
          cp gui/src/HeadTracker ../appdir/usr/bin/
          cp gui/src/css/stylesheet.css ../appdir/usr/bin/
          cp gui/src/css/Background.svg ../appdir/usr/bin/
          cp gui/src/images/Icon256.png ../appdir/usr/share/icons/hicolor/256x256/apps/default.png
          echo -e "[Desktop Entry]\nType=Application\nName=HeadTracker\nExec=HeadTracker\nIcon=default\nCategories=Utility;" > ../appdir/usr/share/applications/HeadTracker.desktop
          wget https://github.com/dlktdr/HeadTracker/raw/master/gui/bin/bossac_lin
          chmod a+x ./bossac_lin
          mv ./bossac_lin ../appdir/usr/bin/
          wget https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
          chmod a+x ./linuxdeployqt-continuous-x86_64.AppImage
          ./linuxdeployqt-continuous-x86_64.AppImage ../appdir/usr/share/applications/HeadTracker.desktop -appimage -verbose=2

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: headtracker_linux_appimage
          path: ${{github.workspace}}/HeadTracker*.AppImage
          retention-days: 60